prompt: RPN Calculator >                                        # Prompt à afficher

languages:
  french: french
  english: english

french:
  help: >                                                       # port of the application (it must be open and free!)
    Bienvenue dans le programme "RPN-Calculator".

    Une calculatrice à Notation Polonaise Inversé (NPI, RPN en anglais pour Reverse Polish Notation).


    Commandes disponibles:


    * 'clear'     | Cette commande permet de réinitialiser la calculatrice, vider la stack utilisée, ainsi que supprimer l'historique affiché.

    * 'quit'      | Cette commande permet de quitter la calculatrice.

    * 'help'      | Cette commande permet d'afficher une aide pour l'utilisateur.

    * 'language' | Cette commande permet d'alterner entre la langue de la calculatrice entre francais et anglais.
  language_switched: >                                          # port of the application (it must be open and free!)
    Changement de language de la calculatrice éffectuée !

    Actuel language : Francais.


  error:
    missing_operand: Impossible d'effectuer le calcul, veuillez entrer au minimum 2 operandes.
    bad_syntax: Mauvaise syntax, l'expression ou la commande entrée est invalide.
    division_by_zero: Opération interdite, la division par 0 est impossible.

english:
  help: >
    Welcome to "RPN-Calculator" software.

    A Reverse Polish Notation calculator (RPN).


    Available commands:


    * 'clear'     | This command allow to reset the RPN calculator, empty stack used, clear displayed history.

    * 'quit'      | This command allow to quit the RPN calculator.

    * 'help'      | This command allow to display an help for users.

    * 'language' | This command allow to switch the RPN calculator language between french and english.
  language_switched: >
    Calculator language well exchanged !

    Current language : English.


  error:
    missing_operand: Impossible to calculate, 2 minimum operands are requiered.
    bad_syntax: Bad syntax, entered expression or command is invalid.
    division_by_zero: Prohibited operation, divide by 0 is impossible.
